name: EC2 Deployment
on:
    workflow_dispatch:

jobs:
    deploy_ec2:
        runs-on: ubuntu-latest

        steps: 
            - name: SSH into EC2 instance and run deploy script
              uses: appleboy/ssh-action@v1
              with:
                host: 44.222.67.240
                username: ec2-user
                key: ${{ secrets.EC2_KEY }}
                script: |
                    pwd
                    ls -l
                    ls -l dice/
                    ls -l dice/resources/
