name: EC2 Deployment

on:
    workflow_dispatch:

jobs:
    deploy_ec2:
        runs-on: ubuntu-latest

        steps:
            - name: SSH into EC2 instance and run deploy script
              uses: appleboy/ssh-action@v1
              with:
                host: 34.205.48.134
                username: ec2-user
                key: ${{ secrets.EC2_KEY }}
                script_path: scripts/deploy_flask_app.sh
